COOKIE_MAX_AGE = 60 * 60 * 24 * 365
COOKIE_NAME_COLOR_MODE = 'mayan_color_mode'

DEFAULT_APPEARANCE_BOOTSTRAP_CARD_LABEL_LINE_COUNT_MAXIMUM = 2
DEFAULT_APPEARANCE_BOOTSTRAP_COLOR_MODE = None
DEFAULT_APPEARANCE_BOOTSTRAP_COLOR_MODE_USER_SELECTION_ENABLED = True

USER_COLOR_MODE_SETTING_KEY = 'color_mode'
USER_COLOR_MODE_SETTING_NAMESPACE = 'appearance_bootstrap'
