DEFAULT_SERVER_SIDE_EVENTS_BACKEND = 'mayan.apps.server_side_events.sse_backends.database.DatabaseServerEventStreamBackend'
DEFAULT_SERVER_SIDE_EVENTS_BACKEND_ARGUMENTS = {}

DEFAULT_SERVER_SIDE_EVENTS_CONNECTION_MAXIMUM_DURATION = 300

DEFAULT_SERVER_SIDE_EVENTS_EVENT_RETENTION = 600

DEFAULT_SERVER_SIDE_EVENTS_KEEPALIVE_INTERVAL = 15

DEFAULT_SERVER_SIDE_EVENTS_POLL_INTERVAL = 2

EVENT_FETCH_MAXIMUM = 100

TASK_STREAM_EVENT_STALE_DELETE_INTERVAL = 60 * 5
