from django.utils.translation import gettext_lazy as _

CONFIG_OPTION_LOG_FAILURE = 'log_failure'
CONFIG_OPTION_LOG_KNOWN_USERS_ONLY = 'log_known_users_only'
CONFIG_OPTION_LOG_SUCCESS = 'log_success'

DEFAULT_AUTHENTICATION_ATTEMPTS_CONFIG = {
    CONFIG_OPTION_LOG_FAILURE: True,
    CONFIG_OPTION_LOG_KNOWN_USERS_ONLY: False,
    CONFIG_OPTION_LOG_SUCCESS: True
}
DEFAULT_LOGIN_ATTEMPT_RETENTION_BACKEND = None
DEFAULT_LOGIN_ATTEMPT_RETENTION_BACKEND_ARGUMENTS = {}
DEFAULT_LOGIN_ATTEMPT_RETENTION_TASK_INTERVAL = 60 * 60 * 24

LOGIN_ATTEMPT_RESULT_FAILURE = 'failure'
LOGIN_ATTEMPT_RESULT_SUCCESS = 'success'

LOGIN_ATTEMPT_RESULT_CHOICES = (
    (LOGIN_ATTEMPT_RESULT_FAILURE, _(message='Failure')),
    (LOGIN_ATTEMPT_RESULT_SUCCESS, _(message='Success'))
)

LOGIN_ATTEMPT_SOURCE_API = 'api'
LOGIN_ATTEMPT_SOURCE_SESSION = 'session'

LOGIN_ATTEMPT_SOURCE_CHOICES = (
    (LOGIN_ATTEMPT_SOURCE_API, _(message='API')),
    (LOGIN_ATTEMPT_SOURCE_SESSION, _(message='Session')),
)
