AUTHENTICATION_LOCKOUT_SETTING_AXES_MAP = {
    'AUTHENTICATION_LOCKOUT_COOLOFF_TIME': 'AXES_COOLOFF_TIME',
    'AUTHENTICATION_LOCKOUT_ENABLED': 'AXES_ENABLED',
    'AUTHENTICATION_LOCKOUT_FAILURE_LIMIT': 'AXES_FAILURE_LIMIT',
    'AUTHENTICATION_LOCKOUT_PARAMETERS': 'AXES_LOCKOUT_PARAMETERS',
    'AUTHENTICATION_LOCKOUT_RESET_ON_SUCCESS': 'AXES_RESET_ON_SUCCESS'
}

AXES_BACKEND_DOTTED_PATH = 'axes.backends.AxesStandaloneBackend'

DEFAULT_AUTHENTICATION_LOCKOUT_COOLOFF_TIME = 0.25
DEFAULT_AUTHENTICATION_LOCKOUT_ENABLED = False
DEFAULT_AUTHENTICATION_LOCKOUT_FAILURE_LIMIT = 5
DEFAULT_AUTHENTICATION_LOCKOUT_PARAMETERS = ['username', 'ip_address']
DEFAULT_AUTHENTICATION_LOCKOUT_RESET_ON_SUCCESS = True

DEFAULT_MAXIMUM_SESSION_LENGTH = 60 * 60 * 24 * 30

DEFAULT_AUTHENTICATION_BACKEND = 'mayan.apps.authentication.authentication_backends.AuthenticationBackendModelDjangoDefault'
DEFAULT_AUTHENTICATION_BACKEND_ARGUMENTS = {
    'maximum_session_length': DEFAULT_MAXIMUM_SESSION_LENGTH
}
DEFAULT_AUTHENTICATION_DISABLE_PASSWORD_RESET = False

DEFAULT_PASSWORD_LENGTH = 10

SESSION_MULTI_FACTOR_USER_BACKEND_KEY = '_multi_factor_user_backend'
SESSION_MULTI_FACTOR_USER_ID_KEY = '_multi_factor_user_id'

USER_IMPERSONATE_VARIABLE_DISABLE = '_user_impersonate_end'
USER_IMPERSONATE_VARIABLE_ID = '_user_impersonate_id'
USER_IMPERSONATE_VARIABLE_PERMANENT = '_user_impersonate_permanent'
