COMMAND_NAME_APPEARANCE_PREPARE_STATIC = 'appearance_prepare_static'

CONTEXT_KEY_APP_TEMPLATE_CACHE_STATE = 'app_template_cache_state'

COOKIE_MAX_AGE = 60 * 60 * 24 * 365

COOKIE_NAME_THEME = 'mayan_theme'
USER_THEME_SETTING_KEY = 'theme'
USER_THEME_SETTING_NAMESPACE = 'appearance'

DEFAULT_APPEARANCE_APP_TEMPLATE_CACHE_VERIFY = False
DEFAULT_APPEARANCE_ELIDED_PAGER_ON_EACH_SIDE = 3
DEFAULT_APPEARANCE_ELIDED_PAGER_ON_ENDS = 1

DEFAULT_APPEARANCE_DATE_TIME_RELATIVE_ENABLE = True

DEFAULT_APPEARANCE_PAGINATION_DROPDOWN_ENABLE = False
DEFAULT_APPEARANCE_PAGINATION_DROPDOWN_RANGE = 100
DEFAULT_APPEARANCE_PAGINATION_INPUT_ENABLE = False

DEFAULT_APPEARANCE_THEME = None
DEFAULT_APPEARANCE_THEME_USER_SELECTION_ENABLED = True

DEFAULT_MAXIMUM_TITLE_LENGTH = 120
DEFAULT_MENU_POLLING_INTERVAL = 5000
DEFAULT_MESSAGE_POSITION = 'bottom-right'
DEFAULT_THROTTLING_MAXIMUM_REQUESTS = 5
DEFAULT_THROTTLING_TIMEOUT = 4000

TAG_APP_TEMPLATE_CACHE_DISABLE = '{% appearance_app_template_cache_disable %}'
