from django.utils.translation import gettext_lazy as _

SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS = 'always'
SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS_KEEP_EMPTY = 'always_keep_if_empty'
SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS_KEEP_ORIGINAL = 'always_keep_original'
SOURCE_UNCOMPRESS_API_CHOICE_NEVER = 'never'

SOURCE_UNCOMPRESS_CHOICE_ALWAYS = 'y'
SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_EMPTY = 'e'
SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_ORIGINAL = 'o'
SOURCE_UNCOMPRESS_CHOICE_ASK = 'a'
SOURCE_UNCOMPRESS_CHOICE_NEVER = 'n'

SOURCE_UNCOMPRESS_API_SLUG_TO_CODE = {
    SOURCE_UNCOMPRESS_API_CHOICE_NEVER: SOURCE_UNCOMPRESS_CHOICE_NEVER,
    SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS: SOURCE_UNCOMPRESS_CHOICE_ALWAYS,
    SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS_KEEP_EMPTY: SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_EMPTY,
    SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS_KEEP_ORIGINAL: SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_ORIGINAL
}

SOURCE_UNCOMPRESS_CHOICES_EXPAND = (
    SOURCE_UNCOMPRESS_CHOICE_ALWAYS,
    SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_EMPTY,
    SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_ORIGINAL
)

TEXT_UNCOMPRESS_ALWAYS = _(message='Always')
TEXT_UNCOMPRESS_ALWAYS_KEEP_EMPTY = _(
    message='Always (or keep the file if it expands to nothing)'
)
TEXT_UNCOMPRESS_ALWAYS_KEEP_ORIGINAL = _(
    message='Always (and also keep the original file)'
)
TEXT_UNCOMPRESS_ASK = _(message='Ask user')
TEXT_UNCOMPRESS_EXPAND = _(message='Expand')
TEXT_UNCOMPRESS_EXPAND_NOT = _(message='Do not expand')
TEXT_UNCOMPRESS_NEVER = _(message='Never')

SOURCE_UNCOMPRESS_API_CHOICES = (
    (SOURCE_UNCOMPRESS_API_CHOICE_NEVER, TEXT_UNCOMPRESS_EXPAND_NOT),
    (SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS, TEXT_UNCOMPRESS_EXPAND),
    (
        SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS_KEEP_EMPTY,
        TEXT_UNCOMPRESS_ALWAYS_KEEP_EMPTY
    ),
    (
        SOURCE_UNCOMPRESS_API_CHOICE_ALWAYS_KEEP_ORIGINAL,
        TEXT_UNCOMPRESS_ALWAYS_KEEP_ORIGINAL
    )
)

SOURCE_UNCOMPRESS_INTERACTIVE_CHOICES = (
    (SOURCE_UNCOMPRESS_CHOICE_ALWAYS, TEXT_UNCOMPRESS_ALWAYS),
    (
        SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_EMPTY,
        TEXT_UNCOMPRESS_ALWAYS_KEEP_EMPTY
    ),
    (
        SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_ORIGINAL,
        TEXT_UNCOMPRESS_ALWAYS_KEEP_ORIGINAL
    ),
    (SOURCE_UNCOMPRESS_CHOICE_NEVER, TEXT_UNCOMPRESS_NEVER),
    (SOURCE_UNCOMPRESS_CHOICE_ASK, TEXT_UNCOMPRESS_ASK)
)

SOURCE_UNCOMPRESS_NON_INTERACTIVE_CHOICES = (
    (SOURCE_UNCOMPRESS_CHOICE_ALWAYS, TEXT_UNCOMPRESS_ALWAYS),
    (
        SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_EMPTY,
        TEXT_UNCOMPRESS_ALWAYS_KEEP_EMPTY
    ),
    (
        SOURCE_UNCOMPRESS_CHOICE_ALWAYS_KEEP_ORIGINAL,
        TEXT_UNCOMPRESS_ALWAYS_KEEP_ORIGINAL

    ),
    (SOURCE_UNCOMPRESS_CHOICE_NEVER, TEXT_UNCOMPRESS_NEVER)
)
