DEFAULT_SERVICE_WORKERS_CACHE_REFRESH_INTERVAL = 600
DEFAULT_SERVICE_WORKERS_ENABLED = True
DEFAULT_SERVICE_WORKERS_RETRY_INTERVAL = 30

URL_FRAGMENT_SERVICE_WORKER_GATEWAY_ERROR = r'service_worker_gateway_error\.html'
URL_FRAGMENT_SERVICE_WORKER_SCRIPT = r'service_worker\.js'

URL_PATTERN_LIST_SESSION_REFRESH_EXEMPT = (
    '^/{}$'.format(URL_FRAGMENT_SERVICE_WORKER_SCRIPT),
    '^/{}$'.format(URL_FRAGMENT_SERVICE_WORKER_GATEWAY_ERROR)
)

URL_REGULAR_SERVICE_WORKER_GATEWAY_ERROR = '^{}$'.format(
    URL_FRAGMENT_SERVICE_WORKER_GATEWAY_ERROR
)
URL_REGULAR_SERVICE_WORKER_SCRIPT = '^{}$'.format(
    URL_FRAGMENT_SERVICE_WORKER_SCRIPT
)
