DEFAULT_CHOICE_FORM_SELECTION_SIZE = 15

DEFAULT_FORMS_COLOR_AUTO_ENABLED = True

DEFAULT_FORMS_DROPZONE_PARALLEL_UPLOADS = 2

DEFAULT_FORMS_SHOW_DROPZONE_SUBMIT_BUTTON = False

EMPTY_LABEL = '---------'

WIDGET_COLOR_ATTRIBUTE_AUTO_ENABLED = 'data-auto-color-enabled'
WIDGET_COLOR_ATTRIBUTE_AUTO_SOURCE = 'data-auto-color-source'

WIDGET_COLOR_CSS_CLASS_AUTO_STATE = 'forms-widget-color-picker-state'

WIDGET_COLOR_NAME_SUFFIX_AUTO_STATE = '_auto_color_enabled'

WIDGET_COLOR_VALUE_FALSE = 'false'
WIDGET_COLOR_VALUE_TRUE = 'true'
