DEFAULT_FILE_METADATA_AUTO_PROCESS = True
DEFAULT_FILE_METADATA_DRIVERS_ARGUMENTS = {}
DEFAULT_FILE_METADATA_MAXIMUM_VALUE_LENGTH = None

ERROR_LOG_DOMAIN_NAME = 'file_metadata'

LOCK_EXPIRE = 60 * 10

MIME_TYPE_WILDCARD = '*'

RESULT_SEPARATOR = '__'

RETRY_BACKOFF = True
RETRY_BACKOFF_MAX = 600
RETRY_JITTER = True

TASK_METADATA_DRIVER_PROCESS_LOCK_NAME_TEMPLATE = 'task_metadata_driver_process-{document_file_id}-{stored_driver_id}'
