COMMAND_NAME_TASK_MANAGER_PURGE_PERIODIC_TASKS = 'task_manager_purge_periodic_tasks'

DEFAULT_CELERY_APP_CLASS = 'celery.Celery'
DEFAULT_CELERY_BROKER_LOGIN_METHOD = 'AMQPLAIN'
DEFAULT_CELERY_BROKER_URL = 'memory://'
DEFAULT_CELERY_BROKER_USE_SSL = None
DEFAULT_CELERY_RESULT_BACKEND = None
DEFAULT_TASK_MANAGER_DEDUPLICATION_BACKEND_MAP = {}
DEFAULT_TASK_MANAGER_DEDUPLICATION_QUEUED_INTERVAL = 86400
DEFAULT_TASK_MANAGER_DEDUPLICATION_STALE_INTERVAL = 3600

TASK_DEDUPLICATION_ENTRY_STALE_DELETE_INTERVAL = 3600

TEST_CELERY_RESULT_KEY = '__mayan_test_result'
TEST_CELERY_RESULT_VALUE = 'test'

WORKER_DEFAULT_CONCURRENCY = 0
