DEFAULT_OCR_AUTO_OCR = True
DEFAULT_OCR_BACKEND = 'mayan.apps.ocr.backends.tesseract.Tesseract'
DEFAULT_OCR_BACKEND_ARGUMENTS = {
    'environment': {'OMP_THREAD_LIMIT': '1'}
}

ERROR_LOG_DOMAIN_NAME = 'ocr'

OCR_IMAGE_FORMAT = 'PNG'

OCR_IMAGE_FORMAT_NATIVE_LIST = ('BMP', 'JPEG', 'PNG', 'TIFF')

OCR_IMAGE_MODE_NATIVE_LIST = ('1', 'L', 'RGB')

TASK_DOCUMENT_VERSION_PAGE_OCR_TIMEOUT = 10 * 60
