DEFAULT_AUTHENTICATION_OIDC_USER_PROFILE_URL = None

DEFAULT_HTTP_TIMEOUT = (5, 15)

DEFAULT_OIDC_OP_AUTHORIZATION_ENDPOINT = None
DEFAULT_OIDC_OP_JWKS_ENDPOINT = None
DEFAULT_OIDC_OP_TOKEN_ENDPOINT = None
DEFAULT_OIDC_OP_USER_ENDPOINT = None

DEFAULT_OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 60 * 15

DEFAULT_OIDC_RP_CLIENT_ID = None
DEFAULT_OIDC_RP_CLIENT_SECRET = None
DEFAULT_OIDC_RP_SIGN_ALGO = 'HS256'

DEFAULT_OIDC_USERNAME_ALGO = 'mayan.apps.authentication_oidc.utils.generate_username_from_email'

HEADER_NAME_LOCATION = 'Location'

HEADER_NAME_REFRESH_URL = 'refresh_url'

PATH_AUTHENTICATION_CLASS_OIDC = (
    'mozilla_django_oidc.contrib.drf.OIDCAuthentication'
)

SCHEME_LIST_PROVIDER = ('http', 'https')

SESSION_KEY_RENEWAL_NEXT = 'mayan_oidc_renewal_next'

SESSION_KEY_STATES = 'oidc_states'

SESSION_KEY_UPSTREAM_NEXT = 'oidc_login_next'

SETTING_NAME_SESSION_REFRESH_EXEMPT_URLS = 'SESSION_REFRESH_EXEMPT_URLS'

STATE_KEY_NEXT = 'mayan_next'

STATUS_CODE_REDIRECT = 302

STATUS_CODE_RENEWAL = 403

URL_NAMESPACE_API = 'rest_api'
