from django.utils.translation import gettext_lazy as _

DEFAULT_VIEWS_OBJECT_LIST_DISPLAY_LIMIT = 100
DEFAULT_VIEWS_PAGINATE_BY = 30
DEFAULT_VIEWS_PAGING_ARGUMENT = 'page'

HEADER_NAME_ALTERNATE_REFERER = 'X-Alt-Referer'
HEADER_NAME_MODAL = 'X-Mayan-Modal'
HEADER_NAME_PAGE_RELOAD = 'X-Mayan-Page-Reload'
HEADER_NAME_REDIRECT_LOCATION = 'X-Mayan-Redirect-Location'

LIST_MODE_CHOICE_ITEM = 'items'
LIST_MODE_CHOICE_LIST = 'list'

LIST_MODE_CHOICES = (
    (LIST_MODE_CHOICE_ITEM, _(message='Items')),
    (LIST_MODE_CHOICE_LIST, _(message='List'))
)

META_KEY_ALTERNATE_REFERER = 'HTTP_X_ALT_REFERER'
META_KEY_REFERER = 'HTTP_REFERER'

MODAL_FRAGMENT_ENABLED = True

PK_LIST_KEY = 'id_list'
PK_LIST_SEPARATOR = ','

REDIRECT_STATUS_CODES = (301, 302, 303, 307, 308)

TEST_SERVER_HOST = 'testserver'
TEST_SERVER_SCHEME = 'http'
TEST_VIEW_NAME = 'test_view_name'
TEST_VIEW_URL = 'test-view-url'

TEXT_LIST_AS_ITEMS_PARAMETER = '_list_mode'
TEXT_LIST_AS_ITEMS_VARIABLE_NAME = 'list_as_items'

TEXT_MODAL_PARAMETER = 'modal'
TEXT_MODAL_VARIABLE_NAME = 'is_modal'

TEXT_SORT_FIELD_PARAMETER = '_ordering'
TEXT_SORT_FIELD_VARIABLE_NAME = 'ordering'

URL_QUERY_POSITIVE_VALUES = ('on', 'true', 'yes')
